const minimalRegex = require("./minimal-regex");

// https://radar.cloudflare.com/domains
const domainList = [
    "google.com",
    "root-servers.net",
    "googleapis.com",
    "apple.com",
    "gstatic.com",
    "cloudflare.com",
    "facebook.com",
    "microsoft.com",
    "amazonaws.com",
    "googlevideo.com",
    "tiktokcdn.com",
    "fbcdn.net",
    "whatsapp.net",
    "doubleclick.net",
    "instagram.com",
    "youtube.com",
    "icloud.com",
    "akadns.net",
    "apple-dns.net",
    "amazon.com",
    "googleusercontent.com",
    "akamai.net",
    "ntp.org",
    "googlesyndication.com",
    "tiktokv.com",
    "live.com",
    "cloudfront.net",
    "cloudflare-dns.com",
    "akamaiedge.net",
    "aaplimg.com",
    "gvt2.com",
    "cdninstagram.com",
    "ytimg.com",
    "netflix.com",
    "bing.com",
    "yahoo.com",
    "cdn77.org",
    "gvt1.com",
    "bytefcdn-oversea.com",
    "taobao.com",
    "office.com",
    "spotify.com",
    "googleadservices.com",
    "samsung.com",
    "tiktokrow-cdn.com",
    "google-analytics.com",
    "snapchat.com",
    "one.one",
    "dns.google",
    "app-analytics-services.com",
    "criteo.com",
    "fastly.net",
    "msftncsi.com",
    "googletagmanager.com",
    "applovin.com",
    "amazon-adsystem.com",
    "wikipedia.org",
    "app-measurement.com",
    "ui.com",
    "trafficmanager.net",
    "unity3d.com",
    "azure.com",
    "steamserver.net",
    "roblox.com",
    "appsflyersdk.com",
    "msn.com",
    "ggpht.com",
    "rocket-cdn.com",
    "skype.com",
    "linkedin.com",
    "baidu.com",
    "sentry.io",
    "tiktokcdn-us.com",
    "a2z.com",
    "rubiconproject.com",
    "office.net",
    "ttlivecdn.com",
    "cdn-apple.com",
    "adnxs.com",
    "windows.net",
    "microsoftonline.com",
    "capcutapi.com",
    "digicert.com",
    "windows.com",
    "xiaomi.com",
    "rbxcdn.com",
    "gmail.com",
    "taboola.com",
    "3gppnetwork.org",
    "android.com",
    "doubleverify.com",
    "qq.com",
    "whatsapp.com",
    "vungle.com",
    "sharepoint.com",
    "office365.com",
    "windowsupdate.com",
    "miui.com",
    "mikrotik.com",
    "pubmatic.com",
];

const pattern = minimalRegex(domainList);
const re = new RegExp("^" + pattern + "$", "i");

console.log(re);

for (const domain of domainList) {
    if (!re.test(domain) || re.test("www." + domain)) {
        throw new Error("Nooo!");
    }
}
